[[pages]]
path = "character.py"
name = "Character Sheet"
icon = "ğŸ“œ"

[[pages]]
path = "events.py"
name = "Events"
icon = "ğŸ“†"

[[pages]]
path = "spellbook.py"
name = "Spellbook"
icon = "ğŸª„"

[[pages]]
path = "skills.py"
name = "Skills"
icon = "ğŸ“–"

[[pages]]
path = "bonus_character.py"
name = "Additional Characters"
icon = "ğŸ‘¥"

[[pages]]
path = "user_guide.py"
name = "User Guide"
icon = "â“"

[[pages]]
path = "user_profile.py"
name = "Profile"
icon = "ğŸªª"

[[pages]]
path = "admin_zone.py"
name = "Admin Zone"
icon = "ğŸ”’"

[[pages]]
name = "User Management"
icon = "ğŸ“‡"
is_section = true

[[pages]]
path = "pages/register_user.py"
name='Register New User'
icon="ğŸ“"

[[pages]]
path = "pages/forgot_username.py"
name='Forgot Username'
icon="ğŸ‘¤"

[[pages]]
path = "pages/forgot_password.py"
name='Forgot Password'
icon="ğŸ”‘"