[[pages]]
path = "character.py"
name = "Character Sheet"
icon = "ğŸ“œ"

[[pages]]
path = "events.py"
name = "Events"
icon = "ğŸ“†"

[[pages]]
path = "spellbook.py"
name = "Spellbook"
icon = "ğŸª„"

[[pages]]
path = "skills.py"
name = "Skills"
icon = "ğŸ“–"

[[pages]]
path = "bonus_character.py"
name = "Additional Characters"
icon = "ğŸ‘¥"

[[pages]]
path = "user_guide.py"
name = "User Guide"
icon = "â“"

[[pages]]
path = "user_profile.py"
name = "Profile"
icon = "ğŸªª"

[[pages]]
path = "admin_zone.py"
name = "Admin Zone"
icon = "ğŸ”’"