[[pages]]
path = "main_page.py"
name = "Character Sheet"
icon = "ğŸ“œ"

[[pages]]
path = "pages/events.py"
name = "Events"
icon = "ğŸ“†"

[[pages]]
path = "pages/user_profile.py"
name = "Profile"
icon = "ğŸªª"

[[pages]]
name = "User Management"
icon = "ğŸ“‡"
is_section = true

[[pages]]
path = "pages/register_user.py"
name='Register New User'
icon="ğŸ“"

[[pages]]
path = "pages/forgot_username.py"
name='Forgot Username'
icon="ğŸ‘¤"

[[pages]]
path = "pages/forgot_password.py"
name='Forgot Password'
icon="ğŸ”‘"